services:
  parser:
    build:
      context: ./parser
    container_name: parser
    ports:
      - "5101:5101"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - phishing-network

  orchestrator:
    build:
      context: ./orchestrator
    container_name: orchestrator
    ports:
      - "5106:5106"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./storage:/app/storage
    depends_on:
      - parser
      - auth
      - content
      - file
      - lien
    networks:
      - phishing-network

  auth:
    build:
      context: ./auth
    container_name: auth
    ports:
      - "5102:5102"
    environment:
      - FLASK_ENV=production
    networks:
      - phishing-network

  content:
    build:
      context: ./content
    container_name: content
    ports:
      - "5103:5103"
    environment:
      - FLASK_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - phishing-network

  file:
    build:
      context: ./file
    container_name: file
    ports:
      - "5104:5104"
    environment:
      - FLASK_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - phishing-network

  lien:
    build:
      context: ./lien
    container_name: lien
    ports:
      - "5105:5105"
    environment:
      - FLASK_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
      - VT_API_KEY=${VT_API_KEY}
      - WHOIS_API_KEY=${WHOIS_API_KEY}
    networks:
      - phishing-network

networks:
  phishing-network:
    driver: bridge
